server:
  port: ${PORT:8080} #服务端口
spring:
  application:
    name: el-framework-govern #指定服务名
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8080/eureka/}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: ${EUREKA_DOMAIN:el.govern}