server:
  port: ${PORT:9091} #服务端口
  servlet:
    context-path: /api
spring:
  application:
    name: el-server-gateway #指定服务名
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
#    password: 123456
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8080/eureka/}
  instance:
    prefer-ip-address:  true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
zuul:
  routes:
    manage-user:
      path: /user/**
      serviceId: el-service-user
      strip-prefix: false
      sensitiveHeaders: